spring.datasource.url=jdbc:mysql://localhost:3306/luxora_db
spring.datasource.username=root
# Use the NEW password you just set in System Settings
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true